# welcome to numpy tutorials


In [1]:
import numpy as np

In [10]:
myarr = np.array([[2,5,6,8]],np.int32)

In [7]:
myarr[2]

6

In [8]:
myarr.shape

(4,)

In [9]:
myarr.dtype

dtype('int32')

In [11]:
myarr[0,2] = 65

In [12]:
myarr

array([[ 2,  5, 65,  8]])

# Array creation : Conversion from other python structures

In [13]:
l = np.array([[2,42,2],[4,5,1],[0,5,1]])

In [14]:
l

array([[ 2, 42,  2],
       [ 4,  5,  1],
       [ 0,  5,  1]])

In [15]:
l.dtype

dtype('int32')

In [16]:
l.shape

(3, 3)

In [17]:
l.size

9

In [18]:
zeros = np.zeros((2,5))

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
zeros.shape

(2, 5)

In [21]:
zeros.size

10

In [22]:
v = np.zeros((3))

In [23]:
v

array([0., 0., 0.])

In [24]:
rng = np.arange(15)

In [25]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
lspace = np.linspace(1,50,10)

In [27]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [29]:
emp = np.empty((4,3))

In [30]:
emp

array([[8.90816340e-312, 2.81617418e-322, 0.00000000e+000],
       [0.00000000e+000, 8.89116236e-312, 2.42336543e-057],
       [4.75702217e-090, 2.49020440e+180, 1.26931307e-076],
       [6.87744535e+169, 6.48224660e+170, 4.93432906e+257]])

In [31]:
emp_like = np.empty_like(lspace)

In [32]:
emp_like

array([8.90816340e-312, 2.81617418e-322, 8.89116236e-312, 2.42336543e-057,
       4.75702217e-090, 2.49020440e+180, 1.26931307e-076, 6.87744535e+169,
       6.48224660e+170, 4.93432906e+257])

In [33]:
ide = np.identity(45)

In [34]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [35]:
arr = np.arange(99)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr =arr.reshape(11,9)

In [39]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [43]:
arr = arr.ravel()

In [44]:
arr.shape

(99,)

# Numpy Axis

In [45]:
x  = [[3,4,2],[2,4,6],[3,2,3]]

In [46]:
ar = np.array(x)

In [47]:
ar

array([[3, 4, 2],
       [2, 4, 6],
       [3, 2, 3]])

In [48]:
ar.sum(axis=0)

array([ 8, 10, 11])

In [49]:
ar.sum(axis=1)

array([ 9, 12,  8])

In [50]:
ar.T

array([[3, 2, 3],
       [4, 4, 2],
       [2, 6, 3]])

In [51]:
ar.flat

In [52]:
for i in ar.flat:
    print(i)

3
4
2
2
4
6
3
2
3


In [53]:
ar.ndim

2

In [54]:
ar.size

9

In [55]:
ar.nbytes

36

In [56]:
one  = np.array([1,2,4,5,6,5])

In [57]:
one.argmax()

4

In [58]:
one.argmin()

0

In [59]:
one.argsort()

array([0, 1, 2, 3, 5, 4], dtype=int64)

In [60]:
ar.argmin()

2

In [61]:
ar.argmax(axis=0)

array([0, 0, 1], dtype=int64)

In [63]:
ar.ravel()

array([3, 4, 2, 2, 4, 6, 3, 2, 3])

In [64]:
ar


array([[3, 4, 2],
       [2, 4, 6],
       [3, 2, 3]])

In [65]:
ar2 = np.array([[2,5,2],[6,3,2],[3,1,0]])

In [66]:
ar2

array([[2, 5, 2],
       [6, 3, 2],
       [3, 1, 0]])

In [67]:
ar + ar2

array([[5, 9, 4],
       [8, 7, 8],
       [6, 3, 3]])

In [68]:
ar*ar2

array([[ 6, 20,  4],
       [12, 12, 12],
       [ 9,  2,  0]])

In [69]:
np.sqrt(ar)

array([[1.73205081, 2.        , 1.41421356],
       [1.41421356, 2.        , 2.44948974],
       [1.73205081, 1.41421356, 1.73205081]])

In [72]:
ar.sum()

29

In [73]:
ar.max()

6

In [75]:
np.where(ar>3)

(array([0, 1, 1], dtype=int64), array([1, 1, 2], dtype=int64))

In [78]:
np.count_nonzero(ar)

9

In [79]:
import sys

In [82]:
py_ar = [0,43,1,5]

In [83]:
np_ar = np.array(py_ar)

In [84]:
sys.getsizeof(1)*len(py_ar)

112

In [85]:
np_ar.itemsize*np_ar.size

16